// Code generated by protoc-gen-natsrpc. DO NOT EDIT.
// versions:
// - protoc-gen-natsrpc v0.7.0
// source: greeter.proto

package api

import (
	context "context"
	natsrpc "github.com/byebyebruce/natsrpc"
	reflect "reflect"
)

var _ context.Context
var _ reflect.Value
var _ = natsrpc.SupportVersion_0_7_0

const (
	Greeter_NRServiceName = "api.Greeter"
)

type GreeterNRClient interface {
	// SayHello - request/response RPC
	SayHello(ctx context.Context, req *HelloRequest, opt ...natsrpc.CallOption) (*HelloReply, error)
	// Notify - publish (no response)
	Notify(notify *NotifyRequest, opt ...natsrpc.CallOption) error
}

type _GreeterNRClientImpl struct {
	c natsrpc.ClientInterface
}

// NewGreeterNRClient
func NewGreeterNRClient(c natsrpc.ClientInterface) GreeterNRClient {
	ret := &_GreeterNRClientImpl{
		c: c,
	}
	return ret
}
func (c *_GreeterNRClientImpl) SayHello(ctx context.Context, req *HelloRequest, opt ...natsrpc.CallOption) (*HelloReply, error) {
	rep := &HelloReply{}
	err := c.c.Request(ctx, Greeter_NRServiceName, "SayHello", req, rep, opt...)
	if err != nil {
		return nil, err
	}
	return rep, err
}
func (c *_GreeterNRClientImpl) Notify(notify *NotifyRequest, opt ...natsrpc.CallOption) error {
	return c.c.Publish(Greeter_NRServiceName, "Notify", notify, opt...)
}

var Greeter_NRServiceDesc = natsrpc.ServiceDesc{
	ServiceName: Greeter_NRServiceName,
	Methods: []natsrpc.MethodDesc{
		{
			MethodName:  "SayHello",
			Handler:     _Greeter_SayHello_NRHandler,
			RequestType: reflect.TypeOf(HelloRequest{}),
			IsPublish:   false,
		},
		{
			MethodName:  "Notify",
			Handler:     _Greeter_Notify_NRHandler,
			RequestType: reflect.TypeOf(NotifyRequest{}),
			IsPublish:   true,
		},
	},
	Metadata: "greeter.proto",
}

type GreeterNRServer interface {
	// SayHello - request/response RPC
	SayHello(ctx context.Context, req *HelloRequest) (*HelloReply, error)
	// Notify - publish (no response)
	Notify(ctx context.Context, req *NotifyRequest) (*Empty, error)
}

func _Greeter_SayHello_NRHandler(svc interface{}, ctx context.Context, req any) (any, error) {
	return svc.(GreeterNRServer).SayHello(ctx, req.(*HelloRequest))
}
func _Greeter_Notify_NRHandler(svc interface{}, ctx context.Context, req any) (any, error) {
	return svc.(GreeterNRServer).Notify(ctx, req.(*NotifyRequest))
}

func RegisterGreeterNRServer(register natsrpc.ServiceRegistrar, s GreeterNRServer, opts ...natsrpc.ServiceOption) (natsrpc.ServiceInterface, error) {
	return register.Register(Greeter_NRServiceDesc, s, opts...)
}
